#!/bin/bash

#general template for pipeline scripts

bids_dir=$1  		#path to bids dir
subjlist=$2		#list of (new) subject IDs to process, where ID is from sub-ID
depends=$3		#job dependencies


job_1=$(neurogliaSubmit -d afterok:$in_depends -j ShortSkinny $POST_BIDS_SCRIPT $BIDS_DIR )



echo $out_depends

