#!/bin/bash

if [ "$#" -lt 1 ]
then
	echo "Locates matching study cfg file, give file or folder formatted as PI_Study_Date_PatientName.*"
	echo "Usage: $0 <input file/folder>"
	exit 1
fi

#env var:
autobids_cfg=$AUTOBIDS_DIR/cfg/study

#input is a tar file from dicom server
in=$1
in_dir=`realpath $in`
in_dir=${in_dir%/*}


in=${in##*/}

#new parsing that allows for underscores in study name
pi=`echo $in | awk  -F '_' '{print $1}'`
pi_study=${in%%_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_*}
study=${pi_study##${pi}_}
date_etc=${in##${pi}_${study}_}
date=${date_etc%%_*}

patient_etc=${date_etc##${date}_}
patient=${patient_etc%%.*}


#echo $pi $study $date $patient

autocfg=$autobids_cfg/${pi}_${study}

#pick the matching cfg file
for cfg in `ls $autobids_cfg/${pi}_${study}*`
do
#	echo cfg: $cfg
	#look for the .<tag> substring in the patient name for a match
	tag=${cfg##*.}
#	echo tag: $tag
	ismatch=`echo $patient | grep -i ${tag}`
	if [ -n "$ismatch" ]
	then
#		echo $cfg is a match with $patient!
		autocfg=$cfg
		continue
	fi	
done
if [ ! -e $autocfg ]
then

	default=$AUTOBIDS_DIR/cfg/study/default
	autocfg=$AUTOBIDS_DIR/cfg/study/${pi}_${study}
	
	if [ -e $default ]  
	then
	 	echo "Study config not found, creating $autocfg from default" >&2 
		cp -v $default $autocfg >&2
	else
	 	echo "Study config not found, and default does not exist: $default" >&2
		exit 1
	fi

	if [ ! -e $autocfg ]
	then
		echo "ERROR in $0: config could not be created: $autocfg (check write-permissions)" >&2
		exit 1
	fi
fi

echo $autocfg
exit 0
