#!/bin/bash

if [ "$#" -lt 2 ]
then
 echo Usage: $0 "<input folder to sync> <globus endpoint to sync to>  <optional arguments for globus cli transfer>"
 exit 1
fi

in_dir=$1
remoteurl=$2
shift 2
optargs=$@

#compose the command

grahamdtn=499930f1-5c43-11e7-bf29-22000b9a448b

localurl=${grahamdtn}:`realpath $in_dir`

datestring=`date +%Y-%m-%d_%I%p`
qfile=$AUTOBIDS_DIR/var/globus_queue/autobids_${datestring}_${RANDOM}


echo Queuing up: globus transfer $localurl $remoteurl $optargs --recursive --notify on
echo globus transfer $localurl $remoteurl $optargs --recursive --notify on  >  $qfile

