#!/bin/bash

#pipeline to run bids-validator

if [ "$#" -lt 2 ]
then
  echo "Usage: $0 <bids> <output txt> <depends - optional>"
  exit 0
fi


bids_dir=$1  		#path to bids dir
out_txt=$2

if [ "$#" -gt 2 ]
then
depends=$3		#job dependencies
fi

if [ -n "$depends" ]
then
	depends_arg="-d $depends"
fi

validator_app=`shub-cache shub://khanlab/bids-validator:0.25.0`
#validator_app=/project/6007967/akhanf/singularity/khanlab-bids-validator-master-0.25.0.simg

jobid_bidsval=$(neurogliaSubmit  $depends_arg -j Quick -N bids-validator -I $validator_app run $bids_dir \> $out_txt )

echo $jobid_bidsval

exit 0
