#!/bin/bash

#pipeline for running gradient correction & sa2rage+mp2rage B1 correction

bids_dir=$1  		#path to bids dir

if [ "$#" -lt 1 ]
then
  echo "Usage: $0 <bids>"
  exit 0
fi
shift 1 
opts=$@
#by default, only run on the most recently submitted subjects
subjlist=`ls -1t $bids_dir/code/*/subjects-list.txt | head -n 1`
if [ -e $subjlist ]
then
	opts="$opts -S $subjlist"
fi


gradcorrect_app=gradcorrect_0.0.1h
mp2rage_correction_app=mp2rage_correction_v0.0.2

job1=$(bidsBatch $opts $gradcorrect_app $bids_dir $bids_dir/derivatives/gradcorrect participant)

#this submits a job when gradcorrect is done, which then runs bidsBatch (needed since bidsBatch requires the input dataset to be complete when the job is run)
job2=$(regularSubmit -j Quick -d afterany:$job1 bidsBatch $opts $mp2rage_correction_app  $bids_dir/derivatives/gradcorrect $bids_dir/derivatives/mp2ragecorrect participant)



#problem with dependencies, since end of mp2rage_correction job is not monitored
echo $job2

exit 0
