#!/bin/bash

function usage {

echo "Usage: $0 <bids> <subjlist>  -f <heuristic> -d <input_dicom_expr> -L <output_log_dir>"

}

if [ "$#" -lt 2 ]
then
	usage
	exit 1
fi

bids_dir=$1
subjlist=$2
shift 2

log_dir=

while getopts "f:d:L:" options; do
 case $options in
  f ) heuristic=$OPTARG;;
  d ) input_string=$OPTARG;;
  L ) log_dir=$OPTARG;;
  * ) usage
      exit 1;;
  esac
done


#SINGULARITY_IMG=`shub-cache shub://khanlab/heudiconv:0.4.3`
SINGULARITY_IMG=/project/6007967/akhanf/singularity/khanlab-heudiconv-master-0.4.3.simg

#SCRATCH_DIR is set by neurogliaBatch inside jobfile
job_dcm2bids=$(neurogliaBatch  heudiconv $subjlist -b "--tempdir \$SCRATCH_DIR -b -d ${input_string} -o $bids_dir -f $heuristic -s" -j 2core8gb )


if [ -n "$log_dir" ]
then
job_heudimove=$(regularSubmit -j Quick -N heudi-mv -d afterany:$job_dcm2bids "mv $bids_dir/.heudiconv $log_dir")
echo $job_heudimove
else
echo $job_dcm2bids
fi

exit 0
