#!/bin/bash

function usage {

echo "Usage: $0 <bids> <subjlist>  -f <heuristic> -d <input_dicom_expr> "

}

if [ "$#" -lt 2 ]
then
	usage
	exit 1
fi

bids_dir=$1
subjlist=$2
shift 2

while getopts "f:d:" options; do
 case $options in
  f ) heuristic=$OPTARG;;
  d ) input_string=$OPTARG;;
  * ) usage
      exit 1;;
  esac
done

SINGULARITY_IMG=/project/6007967/akhanf/singularity/khanlab-heudiconv-master-0.4.3.simg
#SINGULARITY_IMG=shub://akhanf/heudiconv
#SINGULARITY_IMG=/scratch/akhanf/akhanf-heudiconv-master.simg

#SCRATCH_DIR is set by neurogliaBatch inside jobfile
job_dcm2bids=$(neurogliaBatch  heudiconv $subjlist -b "--tempdir \$SCRATCH_DIR -b -d ${input_string} -o $bids_dir -f $heuristic -s" -j 2core8gb )

echo $job_dcm2bids
exit 0
