#!/bin/bash

#pipeline to correct json files in field maps

bids_dir=$1  		#path to bids dir
subjlist=$2		#list of (new) subject IDs to process, where ID is from sub-ID
depends=$3		#job dependencies

jobid=$(neurogliaSubmit -d $depends -j ShortSkinny $AUTOBIDS_DIR/json/correctFieldMap $bids_dir $subjlist )

echo $jobid
