#!/bin/bash

#pipeline to correct json files in field maps, and clean participants.tsv (sort, remove 4th column)

if [ "$#" -lt 1 ]
then
  echo "Usage: $0 <bids> <subjlist> <depends>"
  exit 0
fi


bids_dir=$1  		#path to bids dir
if [ "$#" -gt 1 ]
then
subjlist=$2		#list of (new) subject IDs to process, where ID is from sub-ID
fi

if [ "$#" -gt 2 ]
then
depends=$3		#job dependencies
fi

opts=""
if [ -n "$depends" ]
then
	depends_arg="-d $depends"
fi


jobid_fmap=$(neurogliaSubmit  $depends_arg  -j ShortSkinny $AUTOBIDS_DIR/etc/correctFieldMap $bids_dir $subjlist )
jobid_multiecho=$(neurogliaSubmit  $depends_arg -j ShortSkinny $AUTOBIDS_DIR/etc/correctMultiEcho $bids_dir $subjlist )
jobid_tsv=$(neurogliaSubmit  -d afterany:$jobid_fmap:$jobid_multiecho -j ShortSkinny $AUTOBIDS_DIR/etc/cleanParticipantsFile $bids_dir )

echo $jobid_tsv

exit 0
