#!/bin/bash

#pipeline to correct json files in field maps, and clean participants.tsv (sort, remove 4th column)

if [ "$#" -lt 1 ]
then
  echo "Usage: $0 <bids> <subjlist> <depends>"
  exit 0
fi


bids_dir=$1  		#path to bids dir
if [ "$#" -gt 1 ]
then
subjlist=$2		#list of (new) subject IDs to process, where ID is from sub-ID
fi

if [ "$#" -gt 2 ]
then
depends=$3		#job dependencies
fi

opts=""
if [ -n "$depends" ]
then
	depends_arg="-d $depends"
fi

SINGULARITY_IMG=`shub-cache shub://akhanf/vasst-dev:v0.0.2`
#SINGULARITY_IMG=/project/6007967/akhanf/singularity/akhanf-vasst-dev-master-v0.0.2.simg


jobid_fmap=$(neurogliaSubmit  $depends_arg -N correctFieldMap -j Quick $AUTOBIDS_DIR/etc/correctFieldMap $bids_dir $subjlist )
jobid_multiecho=$(regularSubmit  $depends_arg -j Quick $AUTOBIDS_DIR/etc/correctMultiEcho $bids_dir $subjlist )
jobid_tsv=$(regularSubmit -d afterany:$jobid_fmap:$jobid_multiecho -j Quick $AUTOBIDS_DIR/etc/cleanParticipantsFile $bids_dir )

echo $jobid_tsv

exit 0
