#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Menon/GEvSE
SUBJ_EXPR=*GEvSE_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_DIR/cfg/heuristics/GEvSE.py

DCM2BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/heudiconv_bids
PRE_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/tuneup_bids
#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/mriqc


EMAIL_NOTIFICATION=ostanle2@uwo.ca
