#!/bin/bash


SUBJ_EXPR=*TOPSY_{subject}  #search string for patientname
#SUBJ_EXPR=*.TOPSY.{subject}.*.*  #search string inside tar (from student HD)


HEURISTIC=$AUTOBIDS_DIR/cfg/heuristics/cfmm.py

DCM2BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/heudiconv_bids
PRE_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/tuneup_bids
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/mriqc

EMAIL_NOTIFICATION=alik@robarts.ca

